//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VET_Service_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public string PetName { get; set; }
        public int OwnerID { get; set; }
        public int ProcedureID { get; set; }
        public string TreatmentDate { get; set; }
        public string TreatmentNotes { get; set; }
        public int TreatmentPrice { get; set; }

        [JsonIgnore]
        public virtual Pet Pet { get; set; }
        [JsonIgnore]
        public virtual Procedure Procedure { get; set; }
    }
}
